package org.standict.codelist.delivery;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Writes the {@code downloaded/} and {@code normalized/} trees of every delivery, and republishes them in place.
 *
 * <p>Both trees are generated in full from the downloader's registry, so this pipeline owns them completely and may
 * replace them wholesale. To make sure it never deletes something it did not write, each root carries a
 * {@code delivery-index.json} marker: a root that exists without one is refused rather than removed, which is what
 * would happen if the output path were ever mistyped onto a hand-maintained directory.
 *
 * <p>The trees appear only after every artefact has been extracted, because a half-written delivery looks exactly like
 * a delivery in which the Commission dropped a file.
 */
public final class DeliveryPipeline {
    /** Names a root as generated by this pipeline, and records what it was generated from. */
    static final String INDEX = "delivery-index.json";
    private static final int FORMAT_VERSION = 1;

    private final ObjectMapper json = new ObjectMapper();
    private final DeliveryLayout layout = new DeliveryLayout();
    private final DeliveryExtractor extractor = new DeliveryExtractor();

    public record Result(DeliveryExtractor.Summary summary, String sourcesDigest, Path downloaded, Path normalized) {}

    /**
     * @param downloader checkout of the downloader, which is only ever read
     * @param outputRoot directory receiving the {@code downloaded} and {@code normalized} trees
     */
    public Result run(Path downloader, Path outputRoot) throws IOException {
        Path inputRoot = downloader.toRealPath();
        // Both sides must be resolved the same way, or a symlinked prefix such as /var -> /private/var on macOS
        // makes the containment check below pass for a path that is in fact inside the downloader.
        Path output = resolveThroughExistingParent(outputRoot.toAbsolutePath().normalize());
        if (output.startsWith(inputRoot) || inputRoot.startsWith(output)) {
            throw new IOException("Output must be separate from the downloader repository");
        }
        Path downloadedRoot = output.resolve("downloaded");
        Path normalizedRoot = output.resolve("normalized");
        requireOwnedOrAbsent(downloadedRoot);
        requireOwnedOrAbsent(normalizedRoot);

        List<DeliveryLayout.Artefact> artefacts = layout.read(downloader);
        String digest = sourcesDigest(artefacts);
        Files.createDirectories(output);
        Path staging = Files.createTempDirectory(output, ".deliveries-");
        try {
            Path stagedDownloaded = staging.resolve("downloaded");
            Path stagedNormalized = staging.resolve("normalized");
            DeliveryExtractor.Summary summary = extractor.extract(artefacts, stagedDownloaded, stagedNormalized);
            writeIndex(stagedDownloaded, "downloaded", digest, artefacts, summary);
            writeIndex(stagedNormalized, "normalized", digest, artefacts, summary);
            // Publish only after every artefact of every delivery has been extracted.
            replace(stagedDownloaded, downloadedRoot);
            replace(stagedNormalized, normalizedRoot);
            return new Result(summary, digest, downloadedRoot, normalizedRoot);
        } finally {
            deleteRecursively(staging);
        }
    }

    /** Refuses a root this pipeline cannot prove it generated, so a mistyped output path deletes nothing. */
    private void requireOwnedOrAbsent(Path root) throws IOException {
        if (!Files.exists(root, LinkOption.NOFOLLOW_LINKS)) {
            return;
        }
        if (Files.isSymbolicLink(root) || !Files.isDirectory(root)) {
            throw new IOException("Output root is not a directory: " + root);
        }
        Path index = root.resolve(INDEX);
        if (!Files.isRegularFile(index)) {
            throw new IOException("Refusing to replace " + root + ": no " + INDEX
                    + ", so this directory was not generated here");
        }
        int version = json.readTree(index.toFile()).path("format_version").asInt();
        if (version != FORMAT_VERSION) {
            throw new IOException("Unexpected " + INDEX + " format_version " + version + " in " + root);
        }
    }

    private void writeIndex(Path root, String stage, String digest, List<DeliveryLayout.Artefact> artefacts,
            DeliveryExtractor.Summary summary) throws IOException {
        ObjectNode index = json.createObjectNode();
        index.put("format_version", FORMAT_VERSION);
        index.put("stage", stage);
        index.put("sources_digest", digest);
        index.put("deliveries", summary.deliveries());
        index.put("artefacts", summary.artefacts());
        var deliveries = index.putArray("effective_dates");
        artefacts.stream().map(DeliveryLayout.Artefact::directory).distinct().sorted().forEach(deliveries::add);
        Files.createDirectories(root);
        Files.writeString(root.resolve(INDEX),
                json.writerWithDefaultPrettyPrinter().writeValueAsString(index) + "\n", StandardCharsets.UTF_8);
    }

    /**
     * Identifies the downloader snapshot the trees were generated from. Order-independent by construction, so
     * re-serializing the registry in another key order leaves it unchanged.
     */
    private static String sourcesDigest(List<DeliveryLayout.Artefact> artefacts) {
        String lines = artefacts.stream()
                .map(artefact -> String.join("\t", artefact.url(), artefact.sha256(), artefact.path()))
                .sorted()
                .collect(Collectors.joining("\n"));
        try {
            return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(lines.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    private static void replace(Path staged, Path destination) throws IOException {
        if (Files.exists(destination, LinkOption.NOFOLLOW_LINKS)) {
            deleteRecursively(destination);
        }
        Files.createDirectories(destination.getParent());
        try {
            Files.move(staged, destination, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException e) {
            Files.move(staged, destination);
        }
    }

    /** Resolves symbolic links as far as the path exists, so comparisons against a real path are meaningful. */
    private static Path resolveThroughExistingParent(Path path) throws IOException {
        if (Files.exists(path, LinkOption.NOFOLLOW_LINKS)) {
            return path.toRealPath();
        }
        return resolveThroughExistingParent(path.getParent()).resolve(path.getFileName());
    }

    private static void deleteRecursively(Path root) throws IOException {
        if (!Files.exists(root, LinkOption.NOFOLLOW_LINKS)) {
            return;
        }
        try (var paths = Files.walk(root)) {
            for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) {
                Files.deleteIfExists(path);
            }
        }
    }
}
